/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_csizg_testjni_TestJniApi */

#ifndef _Included_com_csizg_testjni_TestJniApi
#define _Included_com_csizg_testjni_TestJniApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_csizg_testjni_TestJniApi
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_csizg_testjni_TestJniApi_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_csizg_testjni_TestJniApi
 * Method:    setStuList
 * Signature: (Ljava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_csizg_testjni_TestJniApi_setStuList
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_csizg_testjni_TestJniApi
 * Method:    getStuList
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_csizg_testjni_TestJniApi_getStuList
  (JNIEnv *, jobject);

/*
 * Class:     com_csizg_testjni_TestJniApi
 * Method:    setString
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_csizg_testjni_TestJniApi_setString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
